// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqaesgdjuhpstgtiicnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxYWVzZ2RqdWhwc3RndGlpY250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODI0MTAsImV4cCI6MjA3NDY1ODQxMH0.3v9vTMSXOFhwkCBgpXWvShJMNmc6vz9zLyDgAd3Ex60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});